owner: xSlimy1
repo: status

sites:
  - name: EngineCore Repository
    url: https://github.com/xSlimy1/EngineCore
  - name: CurseForge Page
    url: https://www.curseforge.com
  - name: Discord Invite
    url: https://discord.gg

status-website:
  cname: ""
  baseUrl: /status
  logoUrl: https://avatars.githubusercontent.com/xSlimy1
  name: Da-Slimy Project & Status Tracker
  introTitle: "**Live Status & Service Tracker**"
  introMessage: "Real-time uptime, API health, and status monitor for all Da-Slimy mods, tools, and services."
  navbar:
    - title: GitHub
      href: https://github.com/xSlimy1
    - title: Patreon
      href: https://patreon.com/Da_Slimy
